development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: "roundbed_development"
  pool: 5
  username: administrator
  password:
  template: template0

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: "roundbed_test"
  pool: 5
  username: administrator
  password:
  template: template0
